name: Compile Affinity Wine (To Artifact )

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          alsa-utils libcups2 libcups2-dev dosbox ffmpeg fontconfig libfreetype6 libfreetype6-dev gettext libgif7 \
          libgnutls28-dev gstreamer1.0-plugins-base libgstreamer1.0-dev libgtk-3-dev libgphoto2-dev libpcap-dev \
          libpulse-dev libva-dev libxcomposite-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev \
          libosmesa6-dev gcc-mingw-w64 libopencl1 ocl-icd-opencl-dev libpcsclite-dev unixodbc-dev libv4l-dev \
          pulseaudio samba libsane-dev libsdl2-dev v4l-utils mesa-vulkan-drivers libvulkan-dev \
          winetricks mono-complete libcapi20-dev libkrb5-dev libusb-1.0-0-dev \
          liblzma-dev libbz2-dev libcurl4-openssl-dev libsqlite3-dev libp11-kit-dev libunwind-dev \
          libwayland-dev libsmbclient-dev \
          flex libxkbregistry-dev libgstreamer-plugins-base1.0-dev samba-dev oss4-dev libopenal-dev

    - name: Clone Wine repository
      run: |
        git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ${{ github.workspace }}/ElementalWarrior-wine
        cd ${{ github.workspace }}/ElementalWarrior-wine
        git switch affinity-photo3-wine9.13-part3

    - name: Build Wine
      run: |
        CORES=$(nproc)
        mkdir -p ${{ github.workspace }}/winewow64-build/ ${{ github.workspace }}/wine-install/
        cd ${{ github.workspace }}/winewow64-build
        ${{ github.workspace }}/ElementalWarrior-wine/configure --prefix="${{ github.workspace }}/wine-install" --enable-archs=i386,x86_64
        make --jobs $CORES
        make install
     
    - name: Cleanup
      run: |
        rm -rf ${{ github.workspace }}/winewow64-build
        rm -rf ${{ github.workspace }}/ElementalWarrior-wine

    - name: Verify Wine installation
      run: |
        ls -la ${{ github.workspace }}/wine-install
        mv ${{ github.workspace }}/wine-install ${{ github.workspace }}/wine-affinity
        ln -s ${{ github.workspace }}/wine-affinity/bin/wine ${{ github.workspace }}/wine-affinity/bin/wine64

    - name: Archive Wine installation
      run: tar -czvf ${{ github.workspace }}/wine-affinity.tar.gz -C ${{ github.workspace }}/wine-affinity/ .

    - name: Verify tarball creation
      run: ls -la ${{ github.workspace }}/wine-affinity.tar.gz

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Affinity-Wine-Build-${{ github.run_id }}
        path: ${{ github.workspace }}/wine-affinity.tar.gz